# File Handling & Numpy Arrays

Complete the tasks listed below. You can submit the completed lab until 11:59 PM in the night.

### Task 1 (3 marks)

The __data__ folder contains five csv files with column names `Col_A`, `Col_B`, `Col_C`, `Col_D`, and `Col_E`, as well as some fictitious data. Write Python code that extracts all the lines from each file (except the first line which contains the columns names) and creates a list of those integers for each file. For example, the list of integers for the file `Y2015-data.csv` would be [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20].

Then write code that extracts the year (such as `Y2015`) from each file path (such as `data\\Y2015-data.csv`) and creates a key with that year in a dictionary named __data_dict__. The value for the key (e.g. `Y2015`) should be the list of integers extracted from that file (i.e. `Y2015-data.csv`). You can write all of the above mentioned code in a single cell.

Some starter code is reproduced below for your convenience. Also, the desired output __data_dict__ is shown below.

<img src="figs/task1.png" width="1200" height="200" align="left">

In [19]:
import glob

In [20]:
path = '/content/' # use your path
allFiles = []
allFiles = glob.glob(path + "/*.csv")

In [21]:
allFiles

['/content/Y2019-data.csv',
 '/content/Y2015-data.csv',
 '/content/Y2017-data.csv',
 '/content/Y2018-data.csv',
 '/content/Y2016-data.csv']

In [22]:
import csv
data_dict = {}

for file_path in allFiles:
    year_1 = file_path.split('-')[0]
    year=year_1.split('/')[2]
    with open(file_path, 'r') as csvfile:
        reader = csv.reader(csvfile)
        next(reader)
        data = []
        for row in reader:
            data.extend(map(int, row))
        data_dict[year] = data

sorted_data_dict = dict(sorted(data_dict.items(), key=lambda x: x[0]))

print(sorted_data_dict)


{'Y2015': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'Y2016': [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40], 'Y2017': [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], 'Y2018': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80], 'Y2019': [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]}


### Task 2 (0.5 mark)

Write NumPy code to create a 3x3 matrix with values ranging from 2 to 10 (inclusive of both ends).

In [23]:
### Write your code below this comment.

import numpy as np

mat_val = np.arange(2, 11)

mat = mat_val.reshape(3, 3)

print(mat)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Task 3 (0.5 mark)

Write NumPy code to convert the array __[1, 2, 3, 4, 5]__ to float type. Print both the original as well as the converted array.

In [24]:
### Write your code below this comment.
og_arr = [1, 2, 3, 4, 5]

new_arr = np.array(og_arr, dtype=float)

print("Original Array:", og_arr)
print("Converted Array (float):", new_arr)

Original Array: [1, 2, 3, 4, 5]
Converted Array (float): [1. 2. 3. 4. 5.]


### Task 4 (2 marks)

Write NumPy code to create a 5x5 matrix with all 1's. Then write code to modify the matrix such that it has 1 on the borders and 0 inside. Print both the original as well as the modified array. The following is a pictorial representation of such a matrix:

<img src="figs/task4.png" width="250" align="left">

In [25]:
### Write your code below this comment.

og_mat = np.ones((5, 5), dtype=int)

print("\Original Matrix:")
print(og_mat)

og_mat[1:-1, 1:-1]=0
print("\nNew Matrix:")
print(og_mat)

\Original Matrix:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

New Matrix:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Task 5 (2 marks)

Write NumPy code to get the unique elements of the arrays __[10, 10, 20, 20, 30, 30]__ and __[[1, 1], [2, 3]]__. Print both the original arrays as well as the arrays with unique elements. The following is a pictorial representation of this operation:

<img src="figs/task5.png" width="350" height="350" align="left">

In [26]:
### Write your code below this comment.

og_arr1 = np.array([10, 10, 20, 20, 30, 30])
og_arr2 = np.array([[1, 1], [2, 3]])

new_arr1 = np.unique(og_arr1)

new_arr2 = np.unique(og_arr2)

print("Original Array 1:")
print(og_arr1)
print("Unique Array 1:")
print(new_arr1)

print("\nOriginal Array 2:")
print(og_arr2)
print("Unique Array 2:")
print(new_arr2)


Original Array 1:
[10 10 20 20 30 30]
Unique Array 1:
[10 20 30]

Original Array 2:
[[1 1]
 [2 3]]
Unique Array 2:
[1 2 3]


### Task 6 (2 marks)

Write NumPy code to change the dimensions of the 1D array __[1, 2, 3, 4, 5, 6, 7, 8, 9]__ to a 3x3 matrix. Explain why the shape of the 1D array displays 9 rows and no columns although it has just a single row. How could this possibly be corrected?

In [27]:
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = np.array(arr1)
matrix = arr2.reshape(3,3)
print("Shape of 3x3 :",matrix.shape)
#arr2.reshape(3,3)
print("Shape of 1D array :\n" ,arr2.shape)

Shape of 3x3 : (3, 3)
Shape of 1D array :
 (9,)


__Ans:__ As 1D Matrix has no rows or column concept the shape can be seen as 9 rows with no column values. This can be corrected by passing the array as list to new array variable and then using this newly created array the shape can be transformed to 1 row and 9 column values as below.

In [28]:
#arr3 = [[1,2,3,4,5,6,7,8,9]]
arr3 = [arr1]

arr4 = np.array(arr3)
#arr2.reshape(3,3)
print(arr4.shape)

(1, 9)
